databases:
  - name: letseat
    databaseName: letseat
    user: letseat

services:
  - type: web
    name: letseat
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn recipe_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: letseat
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.8.7
